### ISSUE TITLE
loop sim card disable

### ISSUE THREAD

**Issue by mengyyy** [jiefoxi/XposedDisableCarrierPopup#1]

**Comment by mengyyy** [comment]
(com.android.phone  stop  )then  
 (sim card disable)  then
 ( sim card able  )then
(  com.android.phone stop )  loop

**Comment by mengyyy** [comment]
rom   google  factory android 6.0
kernel  ex  
nexus5  d820

**Comment by jiefoxi** [comment]
这个模块只是禁止 STK 弹窗，由于我手头没有 Nexus 5，你的情况难以复现，只能说声抱歉了。

这里有几个尝试方法：
1. 清除电话、联系人应用的缓存后重启看看
2. 能否试试刷回 Google 原厂镜像
3. 删除本模块，如果系统卡在这里了，试试重启进入 Recovery 里删
